name: flutterecommerceapp
description: "A new Flutter project."


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


   #............. packages ...........#
dependencies:
  flutter:
    sdk: flutter

  #icons

  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  #state management
  get: ^4.6.5
  get_storage: ^2.1.1

  # product specific
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  firebase_core: ^2.23.0

  #.......... package end ..............#

dev_dependencies:
  flutter_test:
    sdk: flutter


  #....utility packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_lints: ^2.0.0

  flutter_native_splash: ^2.3.10

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#272727"
  image: assets/logos/shopping-bag.png
  image_dark: assets/logos/shopping-bag (1).png



  web: false






flutter:
  uses-material-design: true

#..............local assets ....... #
  assets:
    - assets/fonts/
    - assets/icons/brand/
    - assets/images/on_boarding_images/
    - assets/logos/
    - assets/images/animations/

#.......... local fonts .......#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500




  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
