// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-ADncE7Gj9AbVnMDia3x4uBlI3u7rN48',
    appId: '1:778835345224:web:c264d104b9c05e894dfd7d',
    messagingSenderId: '778835345224',
    projectId: 'flutter-ecom-app-3d31c',
    authDomain: 'flutter-ecom-app-3d31c.firebaseapp.com',
    storageBucket: 'flutter-ecom-app-3d31c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgbXOphA5JXDAIgoYSug0HcZ8_3CxDt9U',
    appId: '1:778835345224:android:49d2d1c096d85a554dfd7d',
    messagingSenderId: '778835345224',
    projectId: 'flutter-ecom-app-3d31c',
    storageBucket: 'flutter-ecom-app-3d31c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaqRVN2Xz-SFq3saeBncEcUsuAx9KM7E0',
    appId: '1:778835345224:ios:0da0b485f75453ed4dfd7d',
    messagingSenderId: '778835345224',
    projectId: 'flutter-ecom-app-3d31c',
    storageBucket: 'flutter-ecom-app-3d31c.appspot.com',
    iosBundleId: 'com.example.flutterecommerceapp',
  );
}
